"""GENERATED by grid-protocol 0.1.1 from `grid_protocol/schemas/` — do not edit.

Change a schema, then run `python -m grid_protocol._codegen --write`. Each value's comment is the
description the schema gives it; the schema says the rest.
"""
from types import MappingProxyType

PROTOCOL_VERSION = "0.1.1"

#: (cli-error.schema.json)
NO_WAKE_FLAG = "--no-wake"

#: GET /nodes/discover (discover.schema.json)
DISCOVER_PATH = "/nodes/discover"

#: (discover.schema.json/$defs/DiscoveredProvider)
PROVIDER_ROUTE_PREFIX = "provider:"

#: GET /relay/v1/models (models.schema.json)
MODELS_PATH = "/relay/v1/models"

#: POST /nodes/heartbeat (node-heartbeat.schema.json)
HEARTBEAT_PATH = "/nodes/heartbeat"

#: (node-heartbeat.schema.json/$defs/NodeLoad)
UNHEALTHY_MODELS_LOAD_KEY = "unhealthy_models"

#: GET /relay/v1/poll (node-poll.schema.json)
POLL_PATH = "/relay/v1/poll"

#: (node-poll.schema.json)
RELAY_PATH = "/relay/v1"

#: PUT /nodes/{node_id} (node-registration.schema.json)
NODE_PATH = "/nodes/{node_id}"

#: (node-registration.schema.json/$defs/NodeCapabilities/properties/schema_version)
CAPABILITIES_SCHEMA_VERSION = 1

#: POST /relay/v1/response/{transaction_id} (node-upload.schema.json)
RESPONSE_PATH = "/relay/v1/response/{transaction_id}"

#: (node-upload.schema.json)
PROVIDER_ATTEMPT_HEADER = "X-Grid-Provider-Attempt"

#: POST /relay/v1/error/{transaction_id} (node-upload.schema.json/$defs/ErrorReport)
ERROR_REPORT_PATH = "/relay/v1/error/{transaction_id}"

#: (openai-error.schema.json/$defs/NoProvidersAvailable/properties/error/properties/code)
NO_PROVIDERS_AVAILABLE_CODE = "no_providers_available"

#: (openai-error.schema.json/$defs/ModelNotFound/properties/error/properties/code)
MODEL_NOT_FOUND_CODE = "model_not_found"

#: (openai-error.schema.json/$defs/RelayRestarting/properties/error/properties/code)
RELAY_RESTARTING_CODE = "relay_restarting"

#: GET /relay/v1/grid/overview (overview.schema.json)
OVERVIEW_PATH = "/relay/v1/grid/overview"

#: (refusal.schema.json)
RETRY_AFTER_HEADER = "Retry-After"

#: (refusal.schema.json/$defs/GridAsleep/properties/code)
GRID_ASLEEP_CODE = "grid_asleep"

#: (refusal.schema.json/$defs/GridStopped/properties/code)
GRID_STOPPED_CODE = "grid_stopped"

#: (refusal.schema.json/$defs/GridDeleted/properties/code)
GRID_DELETED_CODE = "grid_deleted"

#: (refusal.schema.json/$defs/GridMasterDown/properties/code)
GRID_MASTER_DOWN_CODE = "grid_master_down"

#: (refusal.schema.json/$defs/FeatureRetired/properties/code)
FEATURE_RETIRED_CODE = "feature_retired"

#: How often a provider beats (public CLI `relay.HEARTBEAT_INTERVAL`).
#: (timing.schema.json/properties/heartbeat_interval_seconds)
HEARTBEAT_INTERVAL_SECONDS = 30

#: A node silent this long is not selected (grid-src `NODE_TTL_SECONDS`, a knob; the heartbeat answer's
#: `ttl_seconds`). (timing.schema.json/properties/node_ttl_seconds)
NODE_TTL_SECONDS = 120

#: How long a poll is held before its 204 (grid-src `poll_timeout_seconds`); a provider's own poll timeout
#: must be longer. (timing.schema.json/properties/poll_window_seconds)
POLL_WINDOW_SECONDS = 30

#: A provider parked on grid_asleep probes this often (public CLI `serve._ASLEEP_PROBE_SECONDS`).
#: (timing.schema.json/properties/asleep_probe_seconds)
ASLEEP_PROBE_SECONDS = 10

#: A provider parked on grid_stopped probes this often: only the owner's start ends it.
#: (timing.schema.json/properties/stopped_probe_seconds)
STOPPED_PROBE_SECONDS = 60

#: The next beat after a failed one (the platform's restart of a dead master).
#: (timing.schema.json/properties/after_a_failed_beat_seconds)
AFTER_A_FAILED_BEAT_SECONDS = 10

#: Inside the boot-hold window a request that finds NO provider is held this long for one to beat (grid-src
#: `GRID_BOOT_HOLD_SECONDS`, a knob). A woken master starts with every provider past its TTL.
#: (timing.schema.json/properties/boot_hold_seconds)
BOOT_HOLD_SECONDS = 30

#: How long after a master starts its boot hold applies (grid-src `GRID_BOOT_HOLD_WINDOW_SECONDS`, a knob).
#: (timing.schema.json/properties/boot_hold_window_seconds)
BOOT_HOLD_WINDOW_SECONDS = 120

#: A model is dropped from a reader's list only after this long absent across two or more awake reads (a node
#: TTL and a beat), so a cold wake does not blank a list (harness `GRID_MODEL_RETENTION_SECONDS|_MS`).
#: (timing.schema.json/properties/model_retention_seconds)
MODEL_RETENTION_SECONDS = 150

#: The last-known record is captured only from a master up this long: a node TTL and a beat, with a margin
#: (grid-apis `sleep_record.MIN_UPTIME_SECONDS`).
#: (timing.schema.json/properties/sleep_record_min_uptime_seconds)
SLEEP_RECORD_MIN_UPTIME_SECONDS = 180

#: No record is written until this long after somebody lost access to the grid: their machine can stay listed
#: for a TTL and a beat (grid-apis `sleep_record.ACCESS_LOSS_SETTLE_SECONDS`).
#: (timing.schema.json/properties/access_loss_settle_seconds)
ACCESS_LOSS_SETTLE_SECONDS = 150

#: 29 days: a last-known record older than this is not sent, and a reader ignores one (grid-apis
#: `sleep_record.MAX_AGE_SECONDS`; harness `GRID_LAST_KNOWN_MAX_AGE_SECONDS|_MS`).
#: (timing.schema.json/properties/last_known_max_age_seconds)
LAST_KNOWN_MAX_AGE_SECONDS = 2505600

#: 30 days: a master forgets a node row silent this long (grid-src `registry.prune_stale_nodes`).
#: (timing.schema.json/properties/master_node_prune_seconds)
MASTER_NODE_PRUNE_SECONDS = 2592000

#: Each refusal code, and the HTTP status that carries it.
REFUSAL_STATUS = MappingProxyType({
    "no_providers_available": 503,
    "model_not_found": 404,
    "relay_restarting": 503,
    "grid_asleep": 503,
    "grid_stopped": 503,
    "grid_deleted": 410,
    "grid_master_down": 503,
    "feature_retired": 410,
})
